# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            FourEightThree
tagline:          'Functional .NET, F#, C#'
description:      ''
url:              http://colinbull.github.io
baseurl:          /

author:
  name:           'Colin Bull'
  url:            https://twitter.com/colinbul

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
